import { useState } from 'react'
import { PRESETS, findVibeGradient } from '../utils/vibeColors'
import { generateVibeGradient } from '../utils/vibeAI'

let _idCounter = 0
const newStopId = () => `gs${++_idCounter}`

function Divider({ label }) {
  return (
    <div className="flex items-center gap-3 py-1">
      <span className="text-[8px] uppercase tracking-[0.18em] text-zinc-700">{label}</span>
      <div className="flex-1 h-px bg-zinc-800" />
    </div>
  )
}

const AI_KEY = import.meta.env.VITE_ANTHROPIC_API_KEY ?? ''

export default function GradientControls({ settings, onSettingChange }) {
  const { stops, vibeInput } = settings
  const [vibeLoading, setVibeLoading] = useState(false)
  const [vibeStatus, setVibeStatus]   = useState(null)   // { ok: bool, msg: string } | null

  const sorted      = [...stops].sort((a, b) => a.position - b.position)
  const gradientCSS = `linear-gradient(to right, ${
    sorted.map(s => `${s.color} ${(s.position * 100).toFixed(0)}%`).join(', ')
  })`

  const applyPreset = (preset) =>
    onSettingChange('stops', preset.stops.map(s => ({ ...s, id: newStopId() })))

  const updateStop = (id, key, value) =>
    onSettingChange('stops', stops.map(s => s.id === id ? { ...s, [key]: value } : s))

  const removeStop = (id) => {
    if (stops.length <= 2) return
    onSettingChange('stops', stops.filter(s => s.id !== id))
  }

  const addStop = () => {
    const s   = [...stops].sort((a, b) => a.position - b.position)
    const mid = s.length >= 2
      ? (s[Math.floor((s.length - 1) / 2)].position + s[Math.ceil((s.length - 1) / 2)].position) / 2
      : 0.5
    onSettingChange('stops', [...stops, { id: newStopId(), position: +mid.toFixed(2), color: '#888888' }])
  }

  const handleVibeApply = async () => {
    if (!vibeInput.trim() || vibeLoading) return
    setVibeLoading(true)
    setVibeStatus(null)

    try {
      let stops
      if (AI_KEY) {
        stops = await generateVibeGradient(vibeInput, AI_KEY)
        setVibeStatus({ ok: true, msg: 'Generated by AI' })
      } else {
        stops = findVibeGradient(vibeInput)
        setVibeStatus({ ok: true, msg: 'Keyword match — add VITE_ANTHROPIC_API_KEY to enable AI' })
      }
      if (stops) onSettingChange('stops', stops.map(s => ({ ...s, id: newStopId() })))
    } catch (err) {
      console.error('[Vibe AI]', err)
      const fallback = findVibeGradient(vibeInput)
      if (fallback) onSettingChange('stops', fallback.map(s => ({ ...s, id: newStopId() })))
      setVibeStatus({ ok: false, msg: `AI error — used keyword fallback` })
    } finally {
      setVibeLoading(false)
    }
  }

  return (
    <div className="border-t border-zinc-800/80 bg-zinc-900/60">
      <div className="px-5 py-3 border-b border-zinc-800/50">
        <span className="text-[9px] font-semibold uppercase tracking-[0.18em] text-zinc-400">
          Gradient Map
        </span>
      </div>

      <div className="px-5 py-4 flex flex-col gap-4">

        {/* Preview bar */}
        <div
          className="h-5 w-full border border-zinc-800 shrink-0"
          style={{ background: gradientCSS }}
        />

        <Divider label="Presets" />

        <div className="grid grid-cols-3 gap-1.5">
          {PRESETS.map(preset => (
            <button
              key={preset.name}
              onClick={() => applyPreset(preset)}
              className="px-1 py-1.5 border border-zinc-700 bg-transparent text-zinc-500
                text-[9px] uppercase tracking-[0.06em] hover:border-zinc-500 hover:text-zinc-200
                hover:bg-zinc-800/50 transition-all duration-150 truncate cursor-pointer"
            >
              {preset.name}
            </button>
          ))}
        </div>

        <Divider label="Color Stops" />

        <div className="flex flex-col gap-2.5">
          {sorted.map(stop => (
            <div key={stop.id} className="flex items-center gap-2">

              {/* Colour swatch — click to open picker */}
              <div
                className="w-5 h-5 shrink-0 border border-zinc-700 cursor-pointer"
                style={{ backgroundColor: stop.color }}
                onClick={() => document.getElementById(`gc-${stop.id}`)?.click()}
              />
              <input
                id={`gc-${stop.id}`}
                type="color"
                value={stop.color}
                onChange={e => updateStop(stop.id, 'color', e.target.value)}
                className="sr-only"
              />

              {/* Position slider */}
              <input
                type="range"
                min={0} max={1} step={0.01}
                value={stop.position}
                onChange={e => updateStop(stop.id, 'position', Number(e.target.value))}
                className="flex-1 h-px appearance-none bg-zinc-700 cursor-pointer
                  [&::-webkit-slider-thumb]:appearance-none
                  [&::-webkit-slider-thumb]:w-2.5
                  [&::-webkit-slider-thumb]:h-2.5
                  [&::-webkit-slider-thumb]:bg-zinc-200
                  [&::-webkit-slider-thumb]:cursor-pointer
                  [&::-moz-range-thumb]:w-2.5
                  [&::-moz-range-thumb]:h-2.5
                  [&::-moz-range-thumb]:bg-zinc-200
                  [&::-moz-range-thumb]:border-0
                  [&::-moz-range-thumb]:cursor-pointer"
              />

              {/* Numeric position */}
              <span className="w-6 text-right text-[10px] tabular-nums text-zinc-600 shrink-0">
                {(stop.position * 100).toFixed(0)}
              </span>

              {/* Remove */}
              <button
                onClick={() => removeStop(stop.id)}
                disabled={stops.length <= 2}
                className="shrink-0 text-zinc-700 hover:text-zinc-400 disabled:opacity-20
                  disabled:cursor-not-allowed transition-colors cursor-pointer"
                aria-label="Remove stop"
              >
                <svg viewBox="0 0 16 16" fill="none" stroke="currentColor"
                  strokeWidth="1.5" strokeLinecap="round" className="w-3 h-3">
                  <path d="M4 8h8" />
                </svg>
              </button>
            </div>
          ))}
        </div>

        <button
          onClick={addStop}
          className="flex items-center gap-1.5 text-[9px] uppercase tracking-[0.1em]
            text-zinc-600 hover:text-zinc-400 transition-colors cursor-pointer"
        >
          <svg viewBox="0 0 16 16" fill="none" stroke="currentColor"
            strokeWidth="1.5" strokeLinecap="round" className="w-3 h-3">
            <path d="M8 4v8M4 8h8" />
          </svg>
          Add Stop
        </button>

        {/* AI Vibe header with mode badge */}
        <div className="flex items-center gap-3 py-1">
          <span className="text-[8px] uppercase tracking-[0.18em] text-zinc-700">AI Vibe</span>
          <div className="flex-1 h-px bg-zinc-800" />
          <span className={`text-[8px] uppercase tracking-[0.12em] px-1.5 py-0.5 border ${
            AI_KEY
              ? 'border-zinc-600 text-zinc-400'
              : 'border-zinc-800 text-zinc-700'
          }`}>
            {AI_KEY ? 'AI' : 'Local'}
          </span>
        </div>

        <div className="flex flex-col gap-2">
          <input
            type="text"
            value={vibeInput}
            onChange={e => { onSettingChange('vibeInput', e.target.value); setVibeStatus(null) }}
            onKeyDown={e => { if (e.key === 'Enter') handleVibeApply() }}
            placeholder={AI_KEY ? 'Describe any mood or scene…' : 'Enter a vibe…'}
            className="w-full bg-zinc-950 border border-zinc-800 text-zinc-300 text-[10px]
              px-2.5 py-1.5 placeholder:text-zinc-700 focus:outline-none focus:border-zinc-600
              transition-colors"
          />
          <button
            onClick={handleVibeApply}
            disabled={vibeLoading || !vibeInput.trim()}
            className={`
              w-full py-1.5 text-[10px] uppercase tracking-[0.1em] border transition-all duration-150
              ${vibeLoading || !vibeInput.trim()
                ? 'border-zinc-800 text-zinc-700 cursor-not-allowed'
                : 'border-zinc-700 text-zinc-500 hover:border-zinc-500 hover:text-zinc-200 hover:bg-zinc-800/50 cursor-pointer'
              }
            `}
          >
            {vibeLoading ? 'Generating…' : 'Apply Vibe'}
          </button>

          {/* Status line */}
          {vibeStatus && (
            <p className={`text-[9px] leading-tight ${vibeStatus.ok ? 'text-zinc-600' : 'text-red-800'}`}>
              {vibeStatus.msg}
            </p>
          )}
        </div>

      </div>
    </div>
  )
}
